# Generated by Django 4.2.6 on 2023-10-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='intr_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='depositoptions',
            name='intr_rate2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='depositoptions',
            name='save_trm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='etc_note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='join_deny',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='join_way',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='depositproducts',
            name='spcl_cnd',
            field=models.TextField(),
        ),
    ]
